export const UI_COMPONENT_NAMES = [
    'Section/Parameter group',
    'Heading/Body',
    'Basic button',
    'Icon button',
    'Basic text field',
    'Search text field',
    'Spotlight search text field',
    'Multiline text field',
    'Multiline text field with tags',
    'Switch',
    'Basic select',
    'Basic single choice',
    'Basic multiple choices',
    'Text single choice',
    'Text single choice required',
    'Text multiple choices',
    'Icon single choice',
    'Icon single choice required',
    'Icon multiple choices',
    'Image single choice',
    'Image single choice required',
    'Image multiple choices',
    'Image select',
    'Rich select',
    'Position select',
    'Margin',
    'Padding',
    'Border Width',
    'Border Radius',
    'Range Slider',
    'Range Slider with unit',
    'Icon',
    'Time picker',
    'Date picker',
    'Time period',
    'Color',
    'Custom URL',
    'Image',
    'Font',
    'Single Collection',
    'Multiple Collections',
    'Single Product',
    'Multiple Products',
    'Single Page',
    'Multiple Pages',
    'Single Blog',
    'Multiple Blogs',
    'Single PageFly Page',
    'Single PageFly Product Page',
    'Single PageFly Collection Page',
    'URL',
    'Page section',
    'Email',
    'File',
    'Static item list',
    'Ordered item list',
    'Attribute list',
    'Static text',
    'Icon picker',
    'Divider',
    'Colour picker',
    'Image manager',
    'Font manager',
    'Single collection picker',
    'Multiple collection picker',
    'Collection browser',
    'Collection list',
    'Single Product Picker',
    'Multiple Product Picker',
    'Single Page Picker',
    'Multiple Page Picker',
    'Single Blog Picker',
    'Multiple Blog Picker',
    'Single File Picker',
    'Multiple File Picker',
    'Single PageFly Page Picker',
    'Multiple PageFly Page Picker',
    'URL Picker',
    'Page Section Picker',
    'Email composer',
    'Vendors',
    'Code editor',
    'Static text with CTA',
    'Static text with Title',
    'Help Text'
];
